/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedOverviewRouteImport } from './routes/_authenticated/overview'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedChallengesIndexRouteImport } from './routes/_authenticated/challenges.index'
import { Route as AuthenticatedChallengesIdRouteImport } from './routes/_authenticated/challenges.$id'
import { Route as AuthenticatedEvidenceIndexRouteImport } from './routes/_authenticated/evidence.index'
import { Route as AuthenticatedImpactIndexRouteImport } from './routes/_authenticated/impact.index'
import { Route as AuthenticatedPilotsIndexRouteImport } from './routes/_authenticated/pilots.index'
import { Route as AuthenticatedPilotsIdRouteImport } from './routes/_authenticated/pilots.$id'
import { Route as AuthenticatedScaleIndexRouteImport } from './routes/_authenticated/scale.index'
import { Route as AuthenticatedStartupsIndexRouteImport } from './routes/_authenticated/startups.index'
import { Route as AuthenticatedStartupsIdRouteImport } from './routes/_authenticated/startups.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOverviewRoute = AuthenticatedOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChallengesIndexRoute =
  AuthenticatedChallengesIndexRouteImport.update({
    id: '/challenges/',
    path: '/challenges/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChallengesIdRoute =
  AuthenticatedChallengesIdRouteImport.update({
    id: '/challenges/$id',
    path: '/challenges/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEvidenceIndexRoute =
  AuthenticatedEvidenceIndexRouteImport.update({
    id: '/evidence/',
    path: '/evidence/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedImpactIndexRoute =
  AuthenticatedImpactIndexRouteImport.update({
    id: '/impact/',
    path: '/impact/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPilotsIndexRoute =
  AuthenticatedPilotsIndexRouteImport.update({
    id: '/pilots/',
    path: '/pilots/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPilotsIdRoute = AuthenticatedPilotsIdRouteImport.update({
  id: '/pilots/$id',
  path: '/pilots/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScaleIndexRoute = AuthenticatedScaleIndexRouteImport.update({
  id: '/scale/',
  path: '/scale/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStartupsIndexRoute =
  AuthenticatedStartupsIndexRouteImport.update({
    id: '/startups/',
    path: '/startups/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStartupsIdRoute = AuthenticatedStartupsIdRouteImport.update({
  id: '/startups/$id',
  path: '/startups/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/overview': typeof AuthenticatedOverviewRoute
  '/challenges/$id': typeof AuthenticatedChallengesIdRoute
  '/pilots/$id': typeof AuthenticatedPilotsIdRoute
  '/startups/$id': typeof AuthenticatedStartupsIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/challenges/': typeof AuthenticatedChallengesIndexRoute
  '/evidence/': typeof AuthenticatedEvidenceIndexRoute
  '/impact/': typeof AuthenticatedImpactIndexRoute
  '/pilots/': typeof AuthenticatedPilotsIndexRoute
  '/scale/': typeof AuthenticatedScaleIndexRoute
  '/startups/': typeof AuthenticatedStartupsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/overview': typeof AuthenticatedOverviewRoute
  '/challenges/$id': typeof AuthenticatedChallengesIdRoute
  '/pilots/$id': typeof AuthenticatedPilotsIdRoute
  '/startups/$id': typeof AuthenticatedStartupsIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/challenges': typeof AuthenticatedChallengesIndexRoute
  '/evidence': typeof AuthenticatedEvidenceIndexRoute
  '/impact': typeof AuthenticatedImpactIndexRoute
  '/pilots': typeof AuthenticatedPilotsIndexRoute
  '/scale': typeof AuthenticatedScaleIndexRoute
  '/startups': typeof AuthenticatedStartupsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/overview': typeof AuthenticatedOverviewRoute
  '/_authenticated/challenges/$id': typeof AuthenticatedChallengesIdRoute
  '/_authenticated/pilots/$id': typeof AuthenticatedPilotsIdRoute
  '/_authenticated/startups/$id': typeof AuthenticatedStartupsIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/challenges/': typeof AuthenticatedChallengesIndexRoute
  '/_authenticated/evidence/': typeof AuthenticatedEvidenceIndexRoute
  '/_authenticated/impact/': typeof AuthenticatedImpactIndexRoute
  '/_authenticated/pilots/': typeof AuthenticatedPilotsIndexRoute
  '/_authenticated/scale/': typeof AuthenticatedScaleIndexRoute
  '/_authenticated/startups/': typeof AuthenticatedStartupsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/overview'
    | '/challenges/$id'
    | '/pilots/$id'
    | '/startups/$id'
    | '/admin/'
    | '/challenges/'
    | '/evidence/'
    | '/impact/'
    | '/pilots/'
    | '/scale/'
    | '/startups/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/overview'
    | '/challenges/$id'
    | '/pilots/$id'
    | '/startups/$id'
    | '/admin'
    | '/challenges'
    | '/evidence'
    | '/impact'
    | '/pilots'
    | '/scale'
    | '/startups'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/overview'
    | '/_authenticated/challenges/$id'
    | '/_authenticated/pilots/$id'
    | '/_authenticated/startups/$id'
    | '/_authenticated/admin/'
    | '/_authenticated/challenges/'
    | '/_authenticated/evidence/'
    | '/_authenticated/impact/'
    | '/_authenticated/pilots/'
    | '/_authenticated/scale/'
    | '/_authenticated/startups/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/overview': {
      id: '/_authenticated/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AuthenticatedOverviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/challenges/': {
      id: '/_authenticated/challenges/'
      path: '/challenges'
      fullPath: '/challenges/'
      preLoaderRoute: typeof AuthenticatedChallengesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/challenges/$id': {
      id: '/_authenticated/challenges/$id'
      path: '/challenges/$id'
      fullPath: '/challenges/$id'
      preLoaderRoute: typeof AuthenticatedChallengesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/evidence/': {
      id: '/_authenticated/evidence/'
      path: '/evidence'
      fullPath: '/evidence/'
      preLoaderRoute: typeof AuthenticatedEvidenceIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/impact/': {
      id: '/_authenticated/impact/'
      path: '/impact'
      fullPath: '/impact/'
      preLoaderRoute: typeof AuthenticatedImpactIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pilots/': {
      id: '/_authenticated/pilots/'
      path: '/pilots'
      fullPath: '/pilots/'
      preLoaderRoute: typeof AuthenticatedPilotsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pilots/$id': {
      id: '/_authenticated/pilots/$id'
      path: '/pilots/$id'
      fullPath: '/pilots/$id'
      preLoaderRoute: typeof AuthenticatedPilotsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scale/': {
      id: '/_authenticated/scale/'
      path: '/scale'
      fullPath: '/scale/'
      preLoaderRoute: typeof AuthenticatedScaleIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/startups/': {
      id: '/_authenticated/startups/'
      path: '/startups'
      fullPath: '/startups/'
      preLoaderRoute: typeof AuthenticatedStartupsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/startups/$id': {
      id: '/_authenticated/startups/$id'
      path: '/startups/$id'
      fullPath: '/startups/$id'
      preLoaderRoute: typeof AuthenticatedStartupsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedOverviewRoute: typeof AuthenticatedOverviewRoute
  AuthenticatedChallengesIdRoute: typeof AuthenticatedChallengesIdRoute
  AuthenticatedPilotsIdRoute: typeof AuthenticatedPilotsIdRoute
  AuthenticatedStartupsIdRoute: typeof AuthenticatedStartupsIdRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedChallengesIndexRoute: typeof AuthenticatedChallengesIndexRoute
  AuthenticatedEvidenceIndexRoute: typeof AuthenticatedEvidenceIndexRoute
  AuthenticatedImpactIndexRoute: typeof AuthenticatedImpactIndexRoute
  AuthenticatedPilotsIndexRoute: typeof AuthenticatedPilotsIndexRoute
  AuthenticatedScaleIndexRoute: typeof AuthenticatedScaleIndexRoute
  AuthenticatedStartupsIndexRoute: typeof AuthenticatedStartupsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedOverviewRoute: AuthenticatedOverviewRoute,
  AuthenticatedChallengesIdRoute: AuthenticatedChallengesIdRoute,
  AuthenticatedPilotsIdRoute: AuthenticatedPilotsIdRoute,
  AuthenticatedStartupsIdRoute: AuthenticatedStartupsIdRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedChallengesIndexRoute: AuthenticatedChallengesIndexRoute,
  AuthenticatedEvidenceIndexRoute: AuthenticatedEvidenceIndexRoute,
  AuthenticatedImpactIndexRoute: AuthenticatedImpactIndexRoute,
  AuthenticatedPilotsIndexRoute: AuthenticatedPilotsIndexRoute,
  AuthenticatedScaleIndexRoute: AuthenticatedScaleIndexRoute,
  AuthenticatedStartupsIndexRoute: AuthenticatedStartupsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
