-- Additional government challenges to broaden matching coverage across
-- sectors/departments/states beyond the original 4-challenge seed set.

INSERT INTO public.challenges (
  id, title, problem_statement, department, state, location, sector, category,
  current_process, limitations, beneficiaries, expected_outcome, budget, timeline,
  technologies, capabilities, kpis, eligibility, certifications, priority, deadline, status
) VALUES
('22222222-2222-4222-8222-000000000005','Crop Advisory & Pest Prediction',
 'Smallholder farmers lack timely, localized advisory on pest outbreaks, leading to avoidable yield losses of up to 22%.',
 'Agriculture Department','Punjab','Ludhiana','Agriculture','Precision Farming',
 'Generic advisories broadcast via radio and print bulletins.',
 'No field-level personalization, no early pest-outbreak warning.',
 '310,000 smallholder farmers','Reduce pest-related crop loss by 15% within one cropping season.',
 9500000,'10 months','{"Computer Vision","Remote Sensing","Predictive Analytics"}',
 '{"Field diagnostics app","Satellite/drone imagery ingestion","SMS/IVR advisory"}',
 '[{"kpi":"Pest-related yield loss","baseline":22,"target":15,"unit":"%"},{"kpi":"Advisory response time","baseline":72,"target":6,"unit":"hours"}]',
 'Agri-tech entities with field pilot experience in India.','—','high','2026-12-31','published'),

('22222222-2222-4222-8222-000000000006','Digital Land Records Reconciliation',
 'Over 180,000 land parcels have mismatched paper and digital records, causing disputes and delayed mutations.',
 'Revenue Department','Madhya Pradesh','Bhopal','GovTech','Land Records',
 'Manual reconciliation by revenue clerks during physical surveys.',
 'Slow, error-prone, and creates backlog of pending mutations.',
 '180,000 landholders','Digitally reconcile 90% of flagged parcels within 12 months.',
 14000000,'12 months','{"OCR","NLP","GIS"}',
 '{"Document digitization","Duplicate/conflict detection","Survey workflow integration"}',
 '[{"kpi":"Reconciled parcels","baseline":0,"target":162000,"unit":"parcels"},{"kpi":"Avg mutation time","baseline":45,"target":10,"unit":"days"}]',
 'Registered entity with GIS/OCR deployment record.','ISO 27001 preferred','high','2027-02-28','published'),

('22222222-2222-4222-8222-000000000007','School Dropout Early Warning System',
 'Roughly 9% of enrolled students in government schools drop out annually, often with warning signs going unnoticed.',
 'Education Department','Uttar Pradesh','Lucknow','Education','EdTech',
 'Manual attendance registers reviewed quarterly by block officers.',
 'Warning signs surface too late for timely intervention.',
 '1.2 million enrolled students','Reduce annual dropout rate to under 6% within 2 academic years.',
 11000000,'18 months','{"Predictive Analytics","Mobile App"}',
 '{"Attendance/performance ingestion","Risk scoring","Teacher/parent alerts"}',
 '[{"kpi":"Dropout rate","baseline":9,"target":6,"unit":"%"},{"kpi":"At-risk flag lead time","baseline":0,"target":30,"unit":"days"}]',
 'EdTech entities with government school deployment experience.','—','medium','2027-03-31','published'),

('22222222-2222-4222-8222-000000000008','Grid-Level Solar Rooftop Monitoring',
 'Subsidized rooftop solar installations lack centralized performance monitoring, so underperforming units go undetected for months.',
 'Energy Department','Gujarat','Gandhinagar','Energy','Renewable Energy',
 'Annual manual site inspections by discom field staff.',
 'No real-time fault detection; subsidy fraud and underperformance go unnoticed.',
 '46,000 rooftop installations','Achieve real-time monitoring for 80% of subsidized installations within 12 months.',
 16500000,'12 months','{"IoT","Edge Analytics","Cloud Dashboards"}',
 '{"Remote telemetry","Anomaly/fault detection","Discom dashboard integration"}',
 '[{"kpi":"Monitored installations","baseline":0,"target":36800,"unit":"installations"},{"kpi":"Fault detection time","baseline":90,"target":2,"unit":"days"}]',
 'Energy-tech entities with IoT telemetry deployment record.','BIS compliance','medium','2027-01-15','published'),

('22222222-2222-4222-8222-000000000009','Public Grievance Triage & Routing',
 'Citizen grievances filed on the state portal are manually categorized and routed, causing an average 11-day delay before reaching the right department.',
 'General Administration Department','Odisha','Bhubaneswar','GovTech','Citizen Services',
 'Grievances manually read and tagged by a central desk before routing.',
 'Slow triage, inconsistent categorization, poor SLA tracking.',
 '2.8 million registered portal users','Cut average routing time from 11 days to under 2 days.',
 6000000,'6 months','{"NLP","Classification Models"}',
 '{"Grievance text classification","Department routing engine","SLA dashboard"}',
 '[{"kpi":"Avg routing time","baseline":11,"target":2,"unit":"days"},{"kpi":"Misrouted grievances","baseline":18,"target":5,"unit":"%"}]',
 'GovTech entities with NLP classification experience.','—','medium','2026-11-15','published'),

('22222222-2222-4222-8222-000000000010','Maternal Health Risk Screening',
 'High-risk pregnancies in rural blocks are often identified too late due to infrequent ANC (antenatal care) checkups.',
 'Health Department','Bihar','Patna','Health','Maternal Care',
 'Paper-based ANC registers reviewed monthly by ASHA supervisors.',
 'Delayed risk identification, no predictive flagging between visits.',
 '95,000 pregnant women annually','Identify 90% of high-risk pregnancies at least one trimester earlier.',
 13000000,'14 months','{"AI Triage","Mobile App","Predictive Analytics"}',
 '{"ANC data digitization","Risk scoring model","ASHA mobile workflow"}',
 '[{"kpi":"Early high-risk identification","baseline":40,"target":90,"unit":"%"},{"kpi":"Maternal complications","baseline":6.2,"target":4,"unit":"per 1000"}]',
 'Health-tech entities with maternal/rural health deployment record.','NABH preferred','high','2027-04-30','published'),

('22222222-2222-4222-8222-000000000011','Illegal Construction Detection via Satellite',
 'Unauthorized construction in restricted zones is currently reported only via citizen complaints, missing an estimated 60% of violations.',
 'Urban Development','Haryana','Gurugram','Urban Planning','Compliance',
 'Field inspectors respond only to filed complaints.',
 'Reactive process with significant blind spots and enforcement delays.',
 '1.4 million urban residents','Detect 70% of new unauthorized construction within 30 days of occurrence.',
 10500000,'9 months','{"Satellite Imagery","Computer Vision","GIS"}',
 '{"Change detection","Zoning overlay","Inspector case management"}',
 '[{"kpi":"Detection rate","baseline":40,"target":70,"unit":"%"},{"kpi":"Detection lag","baseline":180,"target":30,"unit":"days"}]',
 'Geospatial/CV entities with municipal compliance experience.','—','medium','2026-12-01','published'),

('22222222-2222-4222-8222-000000000012','Skill-to-Job Matching for Youth',
 'State skilling program graduates face a 34% placement gap because job-matching is done manually against static résumés.',
 'Labour & Skill Development','Telangana','Hyderabad','Employment','Workforce Development',
 'District employment officers manually shortlist candidates from spreadsheets.',
 'Slow, inconsistent matching; poor visibility into regional employer demand.',
 '58,000 skilling program graduates annually','Reduce placement gap from 34% to under 18% within 12 months.',
 8000000,'12 months','{"NLP","Recommendation Systems"}',
 '{"Skill-profile parsing","Employer demand ingestion","Ranked matching engine"}',
 '[{"kpi":"Placement gap","baseline":34,"target":18,"unit":"%"},{"kpi":"Time to placement","baseline":120,"target":45,"unit":"days"}]',
 'Workforce-tech entities with employer network integrations.','—','medium','2027-02-15','published');
